services:
  proxy:
    image: dimajix/llm-monitor
    restart: unless-stopped
    build: .
    ports:
      - "8080:8080"
    environment: &env
      - DB_USER=llm_user
      - DB_PASSWORD=llm_pass
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=llm_monitor
      - UPSTREAM_URL=http://strix.ffm.dimajix.net:11434  # Example upstream
      #- UPSTREAM_URL=http://ollama:11434  # Example upstream
    depends_on:
      db:
        condition: service_healthy

  api:
    image: dimajix/llm-monitor
    restart: unless-stopped
    command: ["./llm-monitor-api", "-c", "/app/config/config.yaml"]
    ports:
      - "8081:8081"
    environment: *env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=llm_user
      - POSTGRES_PASSWORD=llm_pass
      - POSTGRES_DB=llm_monitor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U llm_user -d llm_monitor"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
